FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

# Copy csproj and restore dependencies
COPY *.csproj ./
RUN dotnet restore

# Copy the rest of the code
COPY . .

# Build and run
EXPOSE 80
ENTRYPOINT ["dotnet", "run", "--urls", "http://0.0.0.0:80"] 